# Generated by Django 4.2.3 on 2023-07-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='field1',
            new_name='sw_numer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='field2',
            new_name='sw_password',
        ),
    ]
